
name: test dep

on:
  push:
    branches: [ "main" ]

jobs:
  pre-test:
    runs-on: ubuntu-latest
    steps:
      # deliberately fail
      - run: false
  test:
    runs-on: ubuntu-latest
    needs: [pre-test]
    steps:
      - run: echo hello
