name: test matrix

on: push

jobs:
  test:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
        target:
          - target: linux
            runner: ubuntu-latest
          - target: windows
            runner: windows-latest
          - target: android
            runner: ubuntu-latest
        package: [ prj_a, prj_b ]
        include:
          - target:
              target: linux
              runner: ubuntu-latest
            package: prj_c
        
    # runs-on: ${{ matrix.target.runner }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "building ${{ matrix.package }}-${{ matrix.target.target }} on ${{ matrix.target.runner}}"
