name: test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        runner: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - run: echo $GITHUB_ENV
      - run: set
      - run: echo "REV_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: echo _$REV_SHORT
      - run: echo _${{ env.REV_SHORT }}
