name: test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        runner: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "TEST_PLAIN=Hello_ENV" >> $env.GITHUB_ENV
      - run: echo _${{ env.TEST_PLAIN }}
      - run: echo "REV_SHORT=$(git rev-parse --short HEAD)" >> $env.GITHUB_ENV
      - run: echo _${{ env.REV_SHORT }}
