name: test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        runner: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - if: runner.os != 'Windows'
        run: echo "REV_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - if: runner.os == 'Windows'
        run: echo "REV_SHORT=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV
      - run: echo _${{ env.REV_SHORT }}
